version: "3.9"
services:
  dev:
    container_name: frigate-dev
    user: vscode
    privileged: true
    network_mode: host
    shm_size: "1024mb"
    group_add:
      - dialout
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/lab/frigate:cached
      - ./config/config.yml:/config/config.yml:ro
      - ./debug:/media/frigate
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "1935:1935"
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "5557:5557"
      - "6666:6666"
    entrypoint: ["sudo", "/init"]
    command: /bin/sh -c "while sleep 1000; do :; done"


  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    network_mode: host
    ports:
      - "1883:1883"
