version: "3.9"
services:
  dev:
    container_name: frigate-dev
    user: vscode
    privileged: true
    network_mode: host
    shm_size: "1024mb"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/lab/frigate:cached
      - ./config/config.yml:/config/config.yml:ro
      - ./debug:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
      - /dev/hailo0:/dev/hailo0
    ports:
      - "1935:1935"
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
    entrypoint: ["sudo", "/init"]
    command: /bin/sh -c "while sleep 1000; do :; done"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    network_mode: host
    ports:
      - "1883:1883"
