version: "3.9"
services:
  dev:
    container_name: frigate-dev
    user: vscode
    privileged: true
    network_mode: host
    shm_size: "1024mb"
    group_add:
      - dialout
    build:
      context: .
      dockerfile: docker/Dockerfile.amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/lab/frigate:cached
      - ./config/config.yml:/config/config.yml:ro
      - ./debug:/media/frigate
      - /dev/:/dev/
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    ports:
      - "1935:1935"
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "5557:5557"
      - "5558:5558"
    entrypoint: ["sudo", "/init"]
    command: /bin/sh -c "python3 -u -m frigate"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    network_mode: host
    ports:
      - "1883:1883"
