# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\"\xed\x01\n\x05\x46rame\x12\x11\n\tstream_id\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x1e\n\x04type\x18\x03 \x01(\x0e\x32\x10.Frame.FrameType\x12\x0e\n\x06Height\x18\x04 \x01(\r\x12\r\n\x05Width\x18\x05 \x01(\r\x12\x10\n\x08\x43hannels\x18\x06 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x1e\n\nDetections\x18\x08 \x03(\x0b\x32\n.Detection\x12\x13\n\x0bstream_name\x18\t \x01(\t\"*\n\tFrameType\x12\x07\n\x03RGB\x10\x00\x12\n\n\x06YUV402\x10\x01\x12\x08\n\x04YUY2\x10\x02\"a\n\tDetection\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04xmax\x18\x02 \x01(\x02\x12\x0c\n\x04ymin\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\x12\r\n\x05label\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x02\x62\x06proto3')



_FRAME = DESCRIPTOR.message_types_by_name['Frame']
_DETECTION = DESCRIPTOR.message_types_by_name['Detection']
_FRAME_FRAMETYPE = _FRAME.enum_types_by_name['FrameType']
Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'detection_pb2'
  # @@protoc_insertion_point(class_scope:Detection)
  })
_sym_db.RegisterMessage(Detection)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAME._serialized_start=20
  _FRAME._serialized_end=257
  _FRAME_FRAMETYPE._serialized_start=215
  _FRAME_FRAMETYPE._serialized_end=257
  _DETECTION._serialized_start=259
  _DETECTION._serialized_end=356
# @@protoc_insertion_point(module_scope)
